
version: '3.7'

networks:
  intranet:
    driver: bridge

services:
  kratos-migrate:
    depends_on:
      - auth-db
    container_name: kratos-migrate
    image: oryd/kratos:v0.10.1
    # to run db migrations we use the kratos-cli but don't need to mount the config directory
    # as we only require the DSN to be set as the environment variable for running the migrations
    environment:
      - DSN=postgres://auth:secret@auth-db:5432/auth?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate sql -e --yes
    networks:
      - intranet

  kratos:
    container_name: kratos
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.10.1
    # watch-courier is set for sending verification/recovery emails
    command: serve -c /etc/kratos/config/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./config
        target: /etc/kratos/config
      - type: bind
        source: ./identity-schemas
        target: /etc/kratos/identity-schemas
    ports:
      - 4433:4433 # public
      - 4434:4434 # admin
    networks:
      - intranet

  auth-db:
    image: postgres:alpine
    container_name: auth-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=auth
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - 4436:4436
      - 4437:4437
    networks:
      - intranet

  self-service-go:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: self-service-go
    depends_on:
      - auth-db
      - kratos
    volumes:
      - $PWD:/src
    ports:
      - 4455:4455
    networks:
      - intranet
